### ISSUE TITLE
Got the 100k but not the 350k server cash for Transcendent.

### ISSUE THREAD

**Issue by dfwdatacom** [VoltzModpack/Voltz#60]
Upgraded to Transcendent.  Got 100k upgrade cash, but thought I was supposed to get the 350k as well.

**Comment by kmecpp** [comment]
100k is the intended amount, which is the difference in in game cash that transcendent and  titan receives ($350k vs $250k).  Otherwise everyone buying a rank would just upgrade from each rank to the next to get the upgrade cash.

Is there any indication that you should receive the 350k on the website?

**Comment by dfwdatacom** [comment]
The donor rank states that you get 350k, plus perks + kits. The upgrade gets the perks and the kits, though it says nothing about that.  Since it didn’t specify, I  assumed I  would get the cash as well.  Thought the 100k was an additional incentive to upgrade.  This why I held off upgrading until after the reset. Esp. since my million from before the reset is gone. Guess I would change the text to “You get all of the perks and Kits with the upgrade, but 100k in server money instead of the 350k you get with a full rank.”

 

John
